conditions_weathercom = {
    'Sunny': 'Солнечно',
    "Partly cloudy": "Частично облачно",
    "Cloudy": "Облачно",
    "Overcast": "Пасмурно",
    "Mist": "Туман",
    "Patchy rain possible": "Возможны кратковременные дожди",
    "Patchy snow possible": "Возможны кратковременные снегопады",
    "Patchy sleet possible": "Возможен кратковременный дождь со снегом",
    "Patchy freezing drizzle possible": "Возможна кратковременная замерзающая морось",
    "Thundery outbreaks possible": "Возможны грозовые вспышки",
    "Blowing snow": "Метель",
    "Blizzard": "Метель, буран",
    "Fog": "Туман",
    "Freezing fog": "Морозный туман",
    "Patchy light drizzle": "Небольшой моросящий дождь",
    "Light drizzle": "Небольшой дождь",
    "Freezing drizzle": "Замерзающая морось",
    "Heavy freezing drizzle": "Сильная замерзающая морось",
    "Patchy light rain": "Небольшой кратковременный дождь",
    "Light rain": "Небольшой дождь",
    "Moderate rain at times": "Временами умеренный дождь",
    "Moderate rain": "Умеренный дождь",
    "Heavy rain at times": "Временами сильный дождь",
    "Heavy rain": "Сильный дождь",
    "Light freezing rain": "Небольшой замерзающий дождь",
    "Moderate or heavy freezing rain": "Умеренный или сильный замерзающий дождь",
    "Light sleet": "Небольшой дождь со снегом",
    "Moderate or heavy sleet": "Умеренный или сильный дождь со снегом",
    "Patchy light snow": "Небольшой кратковременный снегопад",
    "Light snow": "Небольшой снегопад",
    "Patchy moderate snow": "Умеренный кратковременный снегопад",
    "Moderate snow": "Умеренный снегопад",
    "Patchy heavy snow": "Сильный кратковременный снегопад",
    "Heavy snow": "Сильный снегопад",
    "Ice pellets": "Ледяные градинки",
    "Light rain shower": "Небольшой дождь",
    "Moderate or heavy rain shower": "Умеренный или сильный дождь",
    "Torrential rain shower": "Ливневый дождь",
    "Light sleet showers": "Неболь"
    }